trigger:
  branches:
    include:
      - feature/*
      - main

pool: agentpool12

stages:
  - stage: Terraformscan
    displayName: scan
    dependsOn: []
    jobs:
      - job: 
        displayName: scan
        steps:
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: 'tfsec .\environment\dev --tfvars-file/environment/dev/terraform'

  - stage: Terraforminit
    displayName: Init
    dependsOn: []
    jobs:
      - job: 
        displayName: Init
        steps:        
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'newadosvc'
            workingDirectory: $(Build.SourcesDirectory)/environment/dev
            backendAzureRmResourceGroupName: 'RG-Backend'
            backendAzureRmStorageAccountName: 'backendstoragevik'
            backendAzureRmContainerName: 'backendcontaine'
            backendAzureRmKey: 'modules.tfstate'

  - stage: Terraformplan
    displayName: Plan
    dependsOn: Terraforminit
    jobs:
      - job: 
        displayName: Plan
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            environmentServiceNameAzureRM: 'newadosvc'
            workingDirectory: $(Build.SourcesDirectory)/environment/dev

  - stage: Terraformapply
    displayName: apply
    dependsOn: Terraformplan
    jobs:
      - job: 
        displayName: apply
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'apply'
            commandOptions: '-auto-approve'
            environmentServiceNameAzureRM: 'newadosvc'
            workingDirectory: $(Build.SourcesDirectory)/environment/dev



