trigger:
  branches:
    include:
      - feature/*
      - main

pool: agentpool12

parameters:
  - name: runTfsec
    displayName: RunTfsec?
    type: boolean

  - name: runTflint
    displayName: RunTflint?
    type: boolean

  - name: runInfracost
    displayName: RunInfracost?
    type: boolean

  - name: runTerraformvalidate
    displayName: RunTerraformvalidate?
    type: boolean

  - name: runTerraformplan
    displayName: RunTerraformplan?
    type: boolean

  - name: runmanualapproval
    displayName: Runmanualapproval?
    type: boolean

  - name: runTerraformapply
    displayName: RunTerraformapply?
    type: boolean

stages:
  - stage: Tfsec
    displayName: Tfsec
    condition: ${{ parameters.runTfsec }}
    dependsOn: []
    jobs:
      - job: Tfsec
        displayName: Tfsec
        steps:
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: 'tfsec $(Build.SourcesDirectory)/environment/dev'
  - stage: Tflint
    displayName: Tflint
    condition: ${{ parameters.runTflint }}
    dependsOn: []
    jobs:
      - job: Tflint
        displayName: Tflint
        steps:
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: 'tflint --recursive --force'
  - stage: Infracost
    displayName: Infracost
    condition: ${{ parameters.runInfracost }}
    dependsOn: []
    jobs:
      - job: Infracost
        displayName: Infracost
        steps:
        - task: InfracostSetup@2
          inputs:
            apiKey: 'ico-Wr0eB6qUSBkRtImO4cmRiEFVabmRvHzQ'
            version: '0.10.x'
            currency: 'INR'

  - stage: Terraformvalidate
    displayName: validate
    condition: ${{ parameters.runTerraformvalidate }}
    dependsOn:
    - tfsec
    - tflint
    - Infracost   
    jobs:
      - job: validate
        displayName: validate
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'newadosvc'
            workingDirectory: $(Build.SourcesDirectory)/environment/dev
            backendAzureRmResourceGroupName: 'RG-Backend'
            backendAzureRmStorageAccountName: 'backendstoragevik'
            backendAzureRmContainerName: 'backendcontainer'
            backendAzureRmKey: 'modules.tfstate'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
  - stage: Terraformplan
    displayName: plan
    condition: ${{ parameters.runTerraformplan }}
    dependsOn: Terraformvalidate

    jobs:
      - job: Plan
        displayName: plan
        steps:        
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'newadosvc'
            workingDirectory: $(Build.SourcesDirectory)/environment/dev
            backendAzureRmResourceGroupName: 'RG-Backend'
            backendAzureRmStorageAccountName: 'backendstoragevik'
            backendAzureRmContainerName: 'backendcontainer'
            backendAzureRmKey: 'modules.tfstate'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            environmentServiceNameAzureRM: 'newadosvc'
            workingDirectory: $(Build.SourcesDirectory)/environment/dev

  - stage: manualapproval
    pool: server
    displayName: approval
    condition: ${{ parameters.runmanualapproval }}
    dependsOn: Terraformplan
    jobs:
      - job: 
        displayName: approval
        steps:
        - task: ManualValidation@1
          inputs:
            notifyUsers: 'abc@gmail.com'
            instructions: 'approve kardo'
       
  - stage: Terraformapply
    displayName: Apply
    condition: ${{ parameters.runTerraformapply }}
    dependsOn: manualapproval
    jobs:
      - job: TerraformApplyJob
        displayName: Terraform Apply
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'newadosvc'
            workingDirectory: $(Build.SourcesDirectory)/environment/dev
            backendAzureRmResourceGroupName: 'RG-Backend'
            backendAzureRmStorageAccountName: 'backendstoragevik'
            backendAzureRmContainerName: 'backendcontainer'
            backendAzureRmKey: 'modules.tfstate'
        - task: TerraformTask@5
          displayName: Terraform Apply
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
            environmentServiceNameAzureRM: 'newadosvc'



