trigger:
  branches:
    include:
      - feature/*
      - main

pool: agentpool12

stages:
  - stage: Terraformscan
    displayName: scan
    jobs:
      - job: 
        displayName: scan
        steps:
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: 'tfsec .\environment\dev --tfvars-file/environment/dev/terraform'
        - task: tfsec@1
          inputs:
            version: 'v1.26.0'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'newadosvc'
            workingDirectory: $(Build.SourcesDirectory)/environment/dev
            backendAzureRmResourceGroupName: 'RG-Backend'
            backendAzureRmStorageAccountName: 'backendstoragevik'
            backendAzureRmContainerName: 'backendcontaine'
            backendAzureRmKey: 'modules.tfstate'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            environmentServiceNameAzureRM: 'newadosvc'
            workingDirectory: $(Build.SourcesDirectory)/environment/dev
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'apply'
            commandOptions: '-auto-approve'
            environmentServiceNameAzureRM: 'newadosvc'
            workingDirectory: $(Build.SourcesDirectory)/environment/dev



